// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBVZKAOgw3CIAf0oZMvQF9oOCkzaYXRPY',
    appId: '1:165947483771:web:cb72ceed62bb3356f224de',
    messagingSenderId: '165947483771',
    projectId: 'cashkingdemo',
    authDomain: 'cashkingdemo.firebaseapp.com',
    storageBucket: 'cashkingdemo.appspot.com',
    measurementId: 'G-1YR1JT66BR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBic6vyAKlmLwTI221F38GSmlksryDFPoE',
    appId: '1:165947483771:android:206e5476a9dea684f224de',
    messagingSenderId: '165947483771',
    projectId: 'cashkingdemo',
    storageBucket: 'cashkingdemo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfqmvIQwDELycTAwcDS_NqyZdn-40SyuY',
    appId: '1:165947483771:ios:1df2ea65ea8d4329f224de',
    messagingSenderId: '165947483771',
    projectId: 'cashkingdemo',
    storageBucket: 'cashkingdemo.appspot.com',
    iosClientId: '165947483771-0gralv9pt2uc7208cba142omfrd77k8p.apps.googleusercontent.com',
    iosBundleId: 'com.cashking.kunal.cashkingdemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfqmvIQwDELycTAwcDS_NqyZdn-40SyuY',
    appId: '1:165947483771:ios:1df2ea65ea8d4329f224de',
    messagingSenderId: '165947483771',
    projectId: 'cashkingdemo',
    storageBucket: 'cashkingdemo.appspot.com',
    iosClientId: '165947483771-0gralv9pt2uc7208cba142omfrd77k8p.apps.googleusercontent.com',
    iosBundleId: 'com.cashking.kunal.cashkingdemo',
  );
}
